name: lhbase_v1
description: lhbase_v1
version: 0.0.2
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  dio: ^4.0.0
  get: 4.3.8
  intl: ^0.17.0

  connectivity: ^3.0.6
  photo_manager: ^2.1.0+2
  equatable: ^2.0.3

  shared_preferences: ^2.0.7
  #  UI
  cached_network_image: ^3.1.0
  flutter_screenutil: ^5.5.3+1
  keyboard_dismisser: ^2.0.0
  lottie: ^1.1.0
  google_fonts: ^2.1.0
  focus_detector: ^2.0.0
  video_player: ^2.4.4
  visibility_detector: ^0.2.2
  flutter_staggered_grid_view: ^0.4.1
  wakelock: ^0.5.6
  photo_view: ^0.14.0

  # resource
  just_audio: ^0.9.24

  # simple state management
  # provider: ^6.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.lhbase.lhbase_v1
        pluginClass: LhbaseV1Plugin

      ios:
        pluginClass: LhbaseV1Plugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/lotties/
    - assets/images/
    - assets/gifs/
